### ISSUE TITLE
the project does not compile

### ISSUE THREAD

**Issue by xSanx** [0r13lc0ch4v1/APCInjector#1]
hi, i use Visual Studio 2019 and get this error : C2664 "NTSTATUS ZwAllocateVirtualMemory (HANDLE, PVOID *, ULONG_PTR, PSIZE_T, ULONG, ULONG)": it is not possible to convert argument 4 from "ULONG *" to "PSIZE_T" in the kernel. apc_dll_injector \ ApcInjectionHandler.cpp 179. Help me please with your project. thank you

**Comment by 0r13lc0ch4v1** [comment]
I don't have the setting you do right now to test it, but when I worked on this project everything compiled.
Maybe VS2019 is more strict.

Try doing C-style cast in the function call:
`(PSIZE_T)&ulSize`

or c++ cast a line before calling it, and use the exact PSIZE_T type:
`PSIZE_T pSize = reinterpret_cast<PSIZE_T>(&ulSize);`
